name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/aditi-rawat.pem
          chmod 600 ~/.ssh/aditi-rawat.pem
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H 51.20.66.120 >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -i ~/.ssh/aditi-rawat.pem ubuntu@51.20.66.120 hostname

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build

      - name: Deploy to Server
        run: |
          scp -i ~/.ssh/aditi-rawat.pem -r build/* ubuntu@51.20.66.120:/var/www/html/my-react-app
          ssh -i ~/.ssh/aditi-rawat.pem ubuntu@51.20.66.120 'sudo systemctl restart nginx'

